// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using FinanceTelegramBot.Data;

#nullable disable

namespace FinanceTelegramBot.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250623084512_ChangeMoneyTransactionTable")]
    partial class ChangeMoneyTransactionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceTelegramBot.Data.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("FinanceTelegramBot.Data.Entities.CategoryKeyword", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.HasKey("Id")
                        .HasName("pk_category_keywords");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_category_keywords_category_id");

                    b.ToTable("category_keywords", (string)null);
                });

            modelBuilder.Entity("FinanceTelegramBot.Data.Entities.MoneyTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("CheckQrCodeRaw")
                        .HasColumnType("text")
                        .HasColumnName("check_qr_code_raw");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_money_transactions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_money_transactions_category_id");

                    b.ToTable("money_transactions", (string)null);
                });

            modelBuilder.Entity("FinanceTelegramBot.Data.Entities.PurchaseItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MoneyTransactionId")
                        .HasColumnType("bigint")
                        .HasColumnName("money_transaction_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_purchase_items");

                    b.HasIndex("MoneyTransactionId")
                        .HasDatabaseName("ix_purchase_items_money_transaction_id");

                    b.ToTable("purchase_items", (string)null);
                });

            modelBuilder.Entity("FinanceTelegramBot.Data.Entities.CategoryKeyword", b =>
                {
                    b.HasOne("FinanceTelegramBot.Data.Entities.Category", "Category")
                        .WithMany("Keywords")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_keywords_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceTelegramBot.Data.Entities.MoneyTransaction", b =>
                {
                    b.HasOne("FinanceTelegramBot.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_money_transactions_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FinanceTelegramBot.Data.Entities.PurchaseItem", b =>
                {
                    b.HasOne("FinanceTelegramBot.Data.Entities.MoneyTransaction", null)
                        .WithMany("Items")
                        .HasForeignKey("MoneyTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_items_money_transactions_money_transaction_id");
                });

            modelBuilder.Entity("FinanceTelegramBot.Data.Entities.Category", b =>
                {
                    b.Navigation("Keywords");
                });

            modelBuilder.Entity("FinanceTelegramBot.Data.Entities.MoneyTransaction", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
