name: Build and Deploy to Server
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        cat > .env << EOF
        PG_CS=${{ secrets.PG_CS }}
        TG_KEY=${{ secrets.TG_KEY }}
        PROVERKA_CHEKA_API_KEY=${{ secrets.PROVERKA_CHEKA_API_KEY }}
        EOF

    - name: Build Docker image
      run: docker compose build

    - name: Stop old containers
      run: docker compose down || true

    - name: Start containers
      run: docker compose up -d